name: Generate PDFs from Markdown

on:
  push:
    branches:
      - main # Trigger workflow on push to the 'main' branch (you can change the branch name)

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc groff ghostscript textlive
      - name: Check Pandoc Version
        run: pandoc --version

      # Step to list markdown files to ensure they exist
      - name: List Markdown Files
        run: |
          echo "Markdown files found:"
          find . -type f -name "*.md"

      - name: Convert Markdown to PDF
        run: |
          set -e # Exit on error
          mkdir -p pdfs # Ensure the 'pdfs' directory exists
          for dir in $(find . -type d); do
            echo "Processing directory: $dir"
            if ls "$dir"/*.md 1> /dev/null 2>&1; then
              mkdir -p "pdfs/$dir" # Create a similar directory structure in the 'pdfs' folder
              for file in "$dir"/*.md; do
                filename=$(basename "$file" .md)
                echo "Converting $file to pdfs/$dir/$filename.pdf"
                pandoc "$file" -o "pdfs/$dir/$filename.pdf"
              done
            fi
          done

      - name: List PDFs
        run: |
          echo "Generated PDFs:"
          find pdfs/ -type f -name "*.pdf"

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: pdfs/
